development:		
  adapter: postgresql		
  encoding: unicode		
  database: database		
  pool: 5		
  min_messages: warning		
  username: username		
  password: password		
  
test:		
  adapter: postgresql		
  encoding: unicode		
  database: database		
  pool: 5		
  min_messages: warning		
  username: username		
  password: password		
